language: python
addons:
  apt:
    packages:
      - libenchant-dev
python:
  - "3.6"
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov
env:
  - TOXENV=test
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=mypy
  - TOXENV=docs
